In [19]:
import numpy as np
print(np.__version__)

1.18.1


In [20]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [22]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 ==1]

array([1, 3, 5, 7, 9])

In [23]:
arr[0:3]

array([0, 1, 2])

In [11]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 ==1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [14]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr2 = arr
arr2[arr2 % 2 ==1] = -1
arr2

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [17]:
np.arange(10)
arr.reshape(2, 5)

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

In [24]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)